springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

nickname:
  blocked-words:
    - 씨발
    - 시발
    - ㅅㅂ
    - 병신
    - 좆
    - ㅈㅈ
    - 개새끼
    - fuck
    - shit
    - bitch
    - asshole
